---
# tasks file for SetupVM
- name: Setup VM
  copy:
   src: {{item}}
   dest: {{dest}}
  loop:
    - "vminsert.service"
    - "vmselect.service"
    - "vmagent.service"
    - "vmstorage.service"
    - "vmalert.service"
- name: Enable VMstorage
  ansible.builtin.service:
   name: {{item}}
   enabled: true
   state: started
  loop:
    - "vminsert.service"
    - "vmselect.service"
    - "vmagent.service"
    - "vmstorage.service"
    - "vmalert.service"
